## Importing neccesary libraries

In [1]:
import pandas as pd
import numpy as np

## Importing the dataset

In [2]:
raw_dataset = pd.read_csv('adult.data')
raw_dataset

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country target  
0              2174             0              40  United-States  <=50K  
1                 0             0              13  United-States  <=50K  
2                 0             0              40  United-States  <=50K  
3                 0             0              40  United-States  <=50K  
4                 0             0              40           Cuba  <=50K  
...             ...           ...             ...            ...    ...  
32556             0             0              38  United-States  <=50K  
32557             0             0              40  United-States   >50K  
32558             0             0              40  United-States  <=50K  
32559             0             0              20  United-States  <=50K  
32560         15024             0              40  United-States   >50K  

[32561 rows x 15 columns]

In [3]:
#dataset = raw_dataset
#for column in raw_dataset.columns:
#    dataset = dataset[dataset[column] != '?']

## Replacing missing values in a column with the most frequent value in the column 

In [4]:
dataset = raw_dataset
for column in raw_dataset.columns:
    dataset[column] = dataset[column].replace(['?'], [dataset[column].value_counts().index[0]])

In [5]:
dataset

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country target  
0              2174             0              40  United-States  <=50K  
1                 0             0              13  United-States  <=50K  
2                 0             0              40  United-States  <=50K  
3                 0             0              40  United-States  <=50K  
4                 0             0              40           Cuba  <=50K  
...             ...           ...             ...            ...    ...  
32556             0             0              38  United-States  <=50K  
32557             0             0              40  United-States   >50K  
32558             0             0              40  United-States  <=50K  
32559             0             0              20  United-States  <=50K  
32560         15024             0              40  United-States   >50K  

[32561 rows x 15 columns]

## Converting all Continuos columns to Categorical columns for Naive Bayes Classifier

In [6]:
dataset['age'] = pd.cut(dataset['age'], [17, 20, 30, 40, 50, 60, 70, 80, 90], right=True, labels=[1, 2, 3, 4, 5, 6, 7, 8], include_lowest=True)

In [7]:
dataset['age'].value_counts()

3    8546
2    8162
4    6983
5    4128
1    2410
6    1792
7     441
8      99
Name: age, dtype: int64

In [8]:
dataset['hours-per-week'] = pd.cut(dataset['hours-per-week'], [1, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100], right=True, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], include_lowest=True)

In [9]:
dataset['hours-per-week'].value_counts()

4     17735
5      5938
6      2533
3      2317
2      2192
1       736
7       612
8       290
10      110
9        98
Name: hours-per-week, dtype: int64

In [10]:
dataset['fnlwgt'] = pd.cut(dataset['fnlwgt'], [0, 150000, 300000, 450000, 600000, 750000, 900000, 1050000, 1200000, 1350000, 1500000], right=True, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], include_lowest=True)

In [11]:
dataset['fnlwgt'].value_counts()

2     16177
1     11972
3      3769
4       501
5       104
6        18
7        10
8         5
10        3
9         2
Name: fnlwgt, dtype: int64

In [12]:
dataset['capital-gain'] = pd.cut(dataset['capital-gain'], [0, 1, 20000, 40000, 80000, 100000], right=True, labels=[1, 2, 3, 4, 5], include_lowest=True)

In [13]:
dataset['capital-gain'].value_counts()

1    29849
2     2459
5      159
3       92
4        2
Name: capital-gain, dtype: int64

In [14]:
dataset['capital-loss'] = pd.cut(dataset['capital-loss'], [0, 1, 1000, 2000, 3000, 4000, 5000], right=True, labels=[1, 2, 3, 4, 5, 6], include_lowest=True)

In [15]:
dataset['capital-loss'].value_counts()

1    31042
3     1158
4      314
2       36
5        8
6        3
Name: capital-loss, dtype: int64

In [16]:
dataset['target'].replace(['>50K', '<=50K'], [1, 0], inplace=True)
dataset

age         workclass fnlwgt   education  education-num  \
0       3         State-gov      1   Bachelors             13   
1       4  Self-emp-not-inc      1   Bachelors             13   
2       3           Private      2     HS-grad              9   
3       5           Private      2        11th              7   
4       2           Private      3   Bachelors             13   
...    ..               ...    ...         ...            ...   
32556   2           Private      2  Assoc-acdm             12   
32557   3           Private      2     HS-grad              9   
32558   5           Private      2     HS-grad              9   
32559   2           Private      2     HS-grad              9   
32560   5      Self-emp-inc      2     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

      capital-gain capital-loss hours-per-week native-country  target  
0                2            1              4  United-States       0  
1                1            1              2  United-States       0  
2                1            1              4  United-States       0  
3                1            1              4  United-States       0  
4                1            1              4           Cuba       0  
...            ...          ...            ...            ...     ...  
32556            1            1              4  United-States       0  
32557            1            1              4  United-States       1  
32558            1            1              4  United-States       0  
32559            1            1              2  United-States       0  
32560            2            1              4  United-States       1  

[32561 rows x 15 columns]

## Spilting the given data into training and testing data

In [17]:
training_data = dataset.sample(frac=2/3)
training_data

age         workclass fnlwgt    education  education-num  \
12513   2           Private      1    Bachelors             13   
13683   3           Private      2      HS-grad              9   
3612    5       Federal-gov      5    Bachelors             13   
19372   3  Self-emp-not-inc      2      HS-grad              9   
14117   4           Private      3  Prof-school             15   
...    ..               ...    ...          ...            ...   
14903   7      Self-emp-inc      3      HS-grad              9   
32153   6           Private      2      5th-6th              3   
31056   3           Private      1    Bachelors             13   
32511   2         Local-gov      4    Bachelors             13   
28033   6           Private      2      7th-8th              4   

           marital-status         occupation   relationship   race     sex  \
12513  Married-civ-spouse     Prof-specialty        Husband  White    Male   
13683  Married-civ-spouse       Craft-repair        Husband  White    Male   
3612   Married-civ-spouse       Tech-support        Husband  Black    Male   
19372       Never-married      Other-service      Unmarried  White    Male   
14117  Married-civ-spouse     Prof-specialty        Husband  White    Male   
...                   ...                ...            ...    ...     ...   
14903  Married-civ-spouse    Exec-managerial        Husband  White    Male   
32153             Widowed  Machine-op-inspct  Not-in-family  White  Female   
31056       Never-married    Exec-managerial  Not-in-family  White  Female   
32511       Never-married       Adm-clerical      Own-child  Black  Female   
28033  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   

      capital-gain capital-loss hours-per-week native-country  target  
12513            1            1              5  United-States       0  
13683            1            1              5  United-States       0  
3612             2            1              4  United-States       1  
19372            1            1              6  United-States       0  
14117            5            1              7  United-States       1  
...            ...          ...            ...            ...     ...  
14903            1            1              4  United-States       1  
32153            1            1              1          Italy       0  
31056            1            3              6  United-States       1  
32511            1            1              4  United-States       0  
28033            1            1              4  United-States       0  

[21707 rows x 15 columns]

In [18]:
testing_data = dataset.drop(training_data.index)
testing_data

age         workclass fnlwgt    education  education-num  \
1       4  Self-emp-not-inc      1    Bachelors             13   
2       3           Private      2      HS-grad              9   
6       4           Private      2          9th              5   
17      3           Private      2      HS-grad              9   
18      3           Private      1         11th              7   
...    ..               ...    ...          ...            ...   
32543   4         Local-gov      1   Assoc-acdm             12   
32546   3           Private      2   Assoc-acdm             12   
32548   6  Self-emp-not-inc      1  Prof-school             15   
32552   4           Private      1    Assoc-voc             11   
32556   2           Private      2   Assoc-acdm             12   

              marital-status         occupation   relationship   race     sex  \
1         Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                   Divorced  Handlers-cleaners  Not-in-family  White    Male   
6      Married-spouse-absent      Other-service  Not-in-family  Black  Female   
17             Never-married  Machine-op-inspct      Unmarried  White    Male   
18        Married-civ-spouse              Sales        Husband  White    Male   
...                      ...                ...            ...    ...     ...   
32543               Divorced     Prof-specialty      Unmarried  White  Female   
32546               Divorced       Tech-support  Not-in-family  White  Female   
32548          Never-married     Prof-specialty  Not-in-family  White    Male   
32552     Married-civ-spouse              Sales        Husband  White    Male   
32556     Married-civ-spouse       Tech-support           Wife  White  Female   

      capital-gain capital-loss hours-per-week native-country  target  
1                1            1              2  United-States       0  
2                1            1              4  United-States       0  
6                1            1              2        Jamaica       0  
17               1            1              4  United-States       0  
18               1            1              5  United-States       0  
...            ...          ...            ...            ...     ...  
32543            1            1              5  United-States       0  
32546            1            1              4  United-States       0  
32548            2            1              6  United-States       0  
32552            1            1              5  United-States       0  
32556            1            1              4  United-States       0  

[10854 rows x 15 columns]

## Function which precomputes all conditional probabilities for each feature in the dataset

In [19]:
def precomp(training_data, alpha):
    prec = []
    positive_data = training_data[training_data['target'] == 1]
    negetive_data = training_data[training_data['target'] == 0]
    
    for column in training_data.columns[:-1]:
        prob = {}
        for value in training_data[column].value_counts().keys():
            prob[value] = []
            prob[value].append((len(negetive_data[negetive_data[column] == value]) + alpha)/(len(negetive_data)+14*alpha))
            prob[value].append((len(positive_data[positive_data[column] == value]) + alpha)/(len(positive_data)+14*alpha))
            prob[-1] = [alpha/(len(negetive_data) + 14*alpha), alpha/(len(positive_data) + 14*alpha)]
        prec.append(prob);
        
    return prec

## Function which returns the prior probability for a given class

In [20]:
def prior(training_data, target):
    return len(training_data[training_data['target'] == target])/len(training_data)

## Function which returns the conditonal probability for a certain feature value given precomputed values, feature, value of feature and the target class

In [21]:
def conditional_prob(prec, feature, value, target):
    if value in prec[feature]:
        prob = prec[feature][value][target]
        
    else:
        prob = 0
        
    if (prob==0):
        prob = prec[feature][-1][target]
    
    return prob

## Function which returns the predicted class for a testing example 

In [22]:
def pred(testing_example, prec, pr1, pr2):
    p1 = pr1
    for i in range(14):
        p1 *= conditional_prob(prec, i, testing_example[i], 1)
    
    p2 = pr2
    for i in range(14):
        p2 *= conditional_prob(prec, i, testing_example[i], 0)
    
    if (p1 > p2):
        return 1
    else:
        return 0

## Function which evaluates the model and returns the confusion matrix

In [23]:
def evaluate(testing_set, prec, pr1, pr2):
    c_mat = np.zeros((2, 2))
    for testing_example in testing_set:
        y = testing_example[14]
        h = pred(testing_example, prec, pr1, pr2)
        if y==1 and h==1:
            c_mat[1][1]+=1
            
        elif y==1 and h==0:
            c_mat[1][0]+=1
            
        elif y==0 and h==0: 
            c_mat[0][0]+=1
            
        else:
            c_mat[0][1]+=1
            
    return c_mat

## Functions for Evaluation Metrics

In [24]:
def accuracy(c_mat):
    return (c_mat[0][0]+c_mat[1][1])/(c_mat[0][0] + c_mat[0][1] + c_mat[1][0] + c_mat[1][1])*100

def precision(c_mat):
    return (c_mat[1][1])/(c_mat[1][1] + c_mat[0][1])*100

def recall(c_mat):
    return (c_mat[1][1])/(c_mat[1][0] + c_mat[1][1])*100

def f1_score(c_mat):
    prec = precision(c_mat)
    rec = recall(c_mat)
    
    return (2*rec*prec)/(prec + rec)

In [25]:
prec = precomp(training_data, 120)
prec

[{3: [0.23336467724984788, 0.24899828277046365],
  -1: [0.006637535261906079, 0.017172295363480253],
  2: [0.2791636705569998, 0.08457355466514024],
  4: [0.16627025831074727, 0.2763308528906697],
  5: [0.1008905359809724, 0.16785918717801945],
  1: [0.09530394380220145, 0.017458500286204923],
  6: [0.056031860169257146, 0.05795649685174585],
  7: [0.019691354610321368, 0.024899828277046364],
  8: [0.009458487748216162, 0.018889524899828276]},
 {'Private': [0.7163559931412136, 0.5216084716657127],
  -1: [0.006637535261906079, 0.017172295363480253],
  'Self-emp-not-inc': [0.07201725759168096, 0.08800801373783629],
  'Local-gov': [0.061839703523424966, 0.07584430452203778],
  'State-gov': [0.042922728026992645, 0.049942759015455064],
  'Self-emp-inc': [0.024337629293655624, 0.07398397252432742],
  'Federal-gov': [0.028596714420045355, 0.05323411562678878],
  'Without-pay': [0.007135350406549034, 0.017172295363480253],
  'Never-worked': [0.006969412025001382, 0.017172295363480253]},
 {2: 

In [26]:
pr1 = prior(training_data, 1)
pr2 = prior(training_data, 0)
pr1 + pr2

1.0

In [27]:
testing_set = testing_data.to_numpy()
c_mat = evaluate(testing_set, prec, pr1, pr2)
acc = accuracy(c_mat)
prec = precision(c_mat)
rec = recall(c_mat)
print(c_mat)
print(f"Accuracy: {acc}")
print(f"Preision: {prec}")
print(f"Recall: {rec}")

[[7668.  653.]
 [1112. 1421.]]
Accuracy: 83.73871383821633
Preision: 68.5149469623915
Recall: 56.0994867745756


## Naive Bayes Classifier using Laplace Smoothing Technique

In [39]:
accuracy_list = np.zeros(10)
precision_list = np.zeros(10)
recall_list = np.zeros(10)
f1_list = np.zeros(10)
for i in range(10):
    
    training_data = dataset.sample(frac=2/3)
    testing_data = dataset.drop(training_data.index)
    testing_set = testing_data.to_numpy()
    
    prec = precomp(training_data, 100)
    pr1 = prior(training_data, 1)
    pr2 = prior(training_data, 0)
    c_mat = evaluate(testing_set, prec, pr1, pr2)
    
    print(f"Model No.{i+1}")
    print(f"Confusion Matrix:\n{c_mat}")
    print(f"Accuracy = {accuracy(c_mat)}")
    print(f"Precision = {precision(c_mat)}")
    print(f"Recall = {recall(c_mat)}")
    print(f"F1-Score = {f1_score(c_mat)}")
    
    accuracy_list[i] =  accuracy(c_mat)
    precision_list[i] = precision(c_mat)
    recall_list[i] =  recall(c_mat)
    f1_list[i] = f1_score(c_mat)
    print("\n")
    
print(f"Accuracy:\n Mean = {accuracy_list.mean()}  Standard Deviation = {accuracy_list.std()}")
print(f"Precision:\n Mean = {precision_list.mean()}  Standard Deviation = {precision_list.std()}")
print(f"Recall:\n Mean = {recall_list.mean()}  Standard Deviation = {recall_list.std()}")
print(f"F1-Score:\n Mean = {f1_list.mean()}  Standard Deviation = {f1_list.std()}")

Model No.1
Confusion Matrix:
[[7577.  694.]
 [1087. 1496.]]
Accuracy = 83.5913027455316
Precision = 68.31050228310502
Recall = 57.91715060007743
F1-Score = 62.685941755709194


Model No.2
Confusion Matrix:
[[7558.  724.]
 [1076. 1496.]]
Accuracy = 83.41625207296849
Precision = 67.38738738738739
Recall = 58.164852255054434
F1-Score = 62.43739565943239


Model No.3
Confusion Matrix:
[[7508.  696.]
 [1122. 1528.]]
Accuracy = 83.25041459369817
Precision = 68.70503597122301
Recall = 57.660377358490564
F1-Score = 62.70004103405826


Model No.4
Confusion Matrix:
[[7513.  778.]
 [1045. 1518.]]
Accuracy = 83.2043486272342
Precision = 66.1149825783972
Recall = 59.227467811158796
F1-Score = 62.48199217946079


Model No.5
Confusion Matrix:
[[7523.  731.]
 [1077. 1523.]]
Accuracy = 83.34254652662612
Precision = 67.56876663708962
Recall = 58.57692307692308
F1-Score = 62.752369180057684


Model No.6
Confusion Matrix:
[[7480.  786.]
 [1098. 1490.]]
Accuracy = 82.64234383637368
Precision = 65.465729349

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [30]:
target = dataset['target']
new_dataset = dataset.drop('target', axis=1)

In [31]:
new_dataset

age         workclass fnlwgt   education  education-num  \
0       3         State-gov      1   Bachelors             13   
1       4  Self-emp-not-inc      1   Bachelors             13   
2       3           Private      2     HS-grad              9   
3       5           Private      2        11th              7   
4       2           Private      3   Bachelors             13   
...    ..               ...    ...         ...            ...   
32556   2           Private      2  Assoc-acdm             12   
32557   3           Private      2     HS-grad              9   
32558   5           Private      2     HS-grad              9   
32559   2           Private      2     HS-grad              9   
32560   5      Self-emp-inc      2     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

      capital-gain capital-loss hours-per-week native-country  
0                2            1              4  United-States  
1                1            1              2  United-States  
2                1            1              4  United-States  
3                1            1              4  United-States  
4                1            1              4           Cuba  
...            ...          ...            ...            ...  
32556            1            1              4  United-States  
32557            1            1              4  United-States  
32558            1            1              4  United-States  
32559            1            1              2  United-States  
32560            2            1              4  United-States  

[32561 rows x 14 columns]

In [32]:
#new_dataset['workclass'].replace(new_dataset['workclass'].value_counts().keys(), list(range(len(new_dataset['workclass'].value_counts()))), inplace=True)
#new_dataset['marital-status'].replace(new_dataset['marital-status'].value_counts().keys(), list(range(len(new_dataset['marital-status'].value_counts()))), inplace=True)
#new_dataset['education'].replace(new_dataset['education'].value_counts().keys(), list(range(len(new_dataset['education'].value_counts()))), inplace=True)
#new_dataset['occupation'].replace(new_dataset['occupation'].value_counts().keys(), list(range(len(new_dataset['occupation'].value_counts()))), inplace=True)
#new_dataset['relationship'].replace(new_dataset['relationship'].value_counts().keys(), list(range(len(new_dataset['relationship'].value_counts()))), inplace=True)
#new_dataset['race'].replace(new_dataset['race'].value_counts().keys(), list(range(len(new_dataset['race'].value_counts()))), inplace=True)
#new_dataset['sex'].replace(new_dataset['sex'].value_counts().keys(), list(range(len(new_dataset['sex'].value_counts()))), inplace=True)
#new_dataset['native-country'].replace(new_dataset['native-country'].value_counts().keys(), list(range(len(new_dataset['native-country'].value_counts()))), inplace=True)

## Converting all Categorical Features to Numerical Features for Logistic Regression and K Nearest-Neighbors

In [33]:
for column in dataset.columns:
    if (dataset[column].dtype == 'object'):
        new_dataset[column].replace(new_dataset[column].value_counts().keys(), list(range(len(new_dataset[column].value_counts()))), inplace=True)

In [34]:
new_dataset

age  workclass fnlwgt  education  education-num  marital-status  \
0       3          3      1          2             13               1   
1       4          1      1          2             13               0   
2       3          0      2          0              9               2   
3       5          0      2          5              7               0   
4       2          0      3          2             13               0   
...    ..        ...    ...        ...            ...             ...   
32556   2          0      2          6             12               0   
32557   3          0      2          0              9               0   
32558   5          0      2          0              9               4   
32559   2          0      2          0              9               1   
32560   5          4      2          0              9               0   

       occupation  relationship  race  sex capital-gain capital-loss  \
0               3             1     0    0            2            1   
1               2             0     0    0            1            1   
2               8             1     0    0            1            1   
3               8             0     1    0            1            1   
4               0             4     1    1            1            1   
...           ...           ...   ...  ...          ...          ...   
32556          10             4     0    1            1            1   
32557           6             0     0    0            1            1   
32558           3             3     0    1            1            1   
32559           3             2     0    0            1            1   
32560           2             4     0    1            2            1   

      hours-per-week  native-country  
0                  4               0  
1                  2               0  
2                  4               0  
3                  4               0  
4                  4               8  
...              ...             ...  
32556              4               0  
32557              4               0  
32558              4               0  
32559              2               0  
32560              4               0  

[32561 rows x 14 columns]

## Logistic Regression using Scikit Learn

In [35]:
# Logistic Regression
accuracy_list = np.zeros(10)
precision_list = np.zeros(10)
recall_list = np.zeros(10)
f1_list = np.zeros(10)
for i in range(10):
    
    x_train, x_test, y_train, y_test = train_test_split(new_dataset, target, test_size=1/3)
    
    logreg = LogisticRegression(max_iter = 10000)
    logreg.fit(x_train, y_train)
    y_pred = logreg.predict(x_test)
    
    print(f"Model No.{i+1}")
    print(f"Confusion Matrix:\n{metrics.confusion_matrix(y_test, y_pred)}")
    print(f"Accuracy = {metrics.accuracy_score(y_test, y_pred)*100}")
    print(f"Precision = {metrics.precision_score(y_test, y_pred)*100}")
    print(f"Recall = {metrics.recall_score(y_test, y_pred)*100}")
    print(f"F1-Score = {metrics.f1_score(y_test, y_pred)*100}")
    
    accuracy_list[i] =  metrics.accuracy_score(y_test, y_pred)*100
    precision_list[i] = metrics.precision_score(y_test, y_pred)*100
    recall_list[i] =  metrics.recall_score(y_test, y_pred)*100
    f1_list[i] = metrics.f1_score(y_test, y_pred)*100
    print("\n")
    
print(f"Accuracy:\n Mean = {accuracy_list.mean()}  Standard Deviation = {accuracy_list.std()}")
print(f"Precision:\n Mean = {precision_list.mean()}  Standard Deviation = {precision_list.std()}")
print(f"Recall:\n Mean = {recall_list.mean()}  Standard Deviation = {recall_list.std()}")
print(f"F1-Score:\n Mean = {f1_list.mean()}  Standard Deviation = {f1_list.std()}")

Model No.1
Confusion Matrix:
[[7685  533]
 [1325 1311]]
Accuracy = 82.88188686198636
Precision = 71.09544468546638
Recall = 49.73444613050076
F1-Score = 58.52678571428572


Model No.2
Confusion Matrix:
[[7627  565]
 [1297 1365]]
Accuracy = 82.84503408881518
Precision = 70.72538860103627
Recall = 51.27723516153269
F1-Score = 59.45121951219512


Model No.3
Confusion Matrix:
[[7708  529]
 [1296 1321]]
Accuracy = 83.18592224064861
Precision = 71.4054054054054
Recall = 50.47764615972488
F1-Score = 59.1448399373181


Model No.4
Confusion Matrix:
[[7668  594]
 [1251 1341]]
Accuracy = 83.00165837479271
Precision = 69.30232558139535
Recall = 51.736111111111114
F1-Score = 59.24453280318092


Model No.5
Confusion Matrix:
[[7657  594]
 [1286 1317]]
Accuracy = 82.67919660954487
Precision = 68.91679748822605
Recall = 50.59546676911256
F1-Score = 58.3517944173682


Model No.6
Confusion Matrix:
[[7679  551]
 [1295 1329]]
Accuracy = 82.9924451814999
Precision = 70.69148936170212
Recall = 50.64786585365

## K Nearest Neighbors (1 Neighbor) using Scikit Learn

In [36]:
# K Nearest Neighbours (No. of Neighbors = 1)
accuracy_list = np.zeros(10)
precision_list = np.zeros(10)
recall_list = np.zeros(10)
f1_list = np.zeros(10)
for i in range(10):
    
    x_train, x_test, y_train, y_test = train_test_split(new_dataset, target, test_size=1/3)
    
    knn = KNeighborsClassifier(n_neighbors=1)
    knn.fit(x_train, y_train)
    y_pred = knn.predict(x_test)
    
    print(f"Model No.{i+1}")
    print(f"Confusion Matrix:\n{metrics.confusion_matrix(y_test, y_pred)}")
    print(f"Accuracy = {metrics.accuracy_score(y_test, y_pred)*100}")
    print(f"Precision = {metrics.precision_score(y_test, y_pred)*100}")
    print(f"Recall = {metrics.recall_score(y_test, y_pred)*100}")
    print(f"F1-Score = {metrics.f1_score(y_test, y_pred)*100}")
    
    accuracy_list[i] =  metrics.accuracy_score(y_test, y_pred)*100
    precision_list[i] = metrics.precision_score(y_test, y_pred)*100
    recall_list[i] =  metrics.recall_score(y_test, y_pred)*100
    f1_list[i] = metrics.f1_score(y_test, y_pred)*100
    print("\n")
    
print(f"Accuracy:\n Mean = {accuracy_list.mean()}  Standard Deviation = {accuracy_list.std()}")
print(f"Precision:\n Mean = {precision_list.mean()}  Standard Deviation = {precision_list.std()}")
print(f"Recall:\n Mean = {recall_list.mean()}  Standard Deviation = {recall_list.std()}")
print(f"F1-Score:\n Mean = {f1_list.mean()}  Standard Deviation = {f1_list.std()}")

Model No.1
Confusion Matrix:
[[7146 1102]
 [1162 1444]]
Accuracy = 79.14133038511147
Precision = 56.71641791044776
Recall = 55.41059094397545
F1-Score = 56.05590062111801


Model No.2
Confusion Matrix:
[[7156 1101]
 [1140 1457]]
Accuracy = 79.35323383084577
Precision = 56.95856137607505
Recall = 56.10319599537929
F1-Score = 56.527643064985455


Model No.3
Confusion Matrix:
[[7143 1082]
 [1152 1477]]
Accuracy = 79.41772618389534
Precision = 57.7178585384916
Recall = 56.18105743628756
F1-Score = 56.939090208172715


Model No.4
Confusion Matrix:
[[7103 1113]
 [1171 1467]]
Accuracy = 78.95706651925558
Precision = 56.860465116279066
Recall = 55.61031084154663
F1-Score = 56.228440015331536


Model No.5
Confusion Matrix:
[[7124 1089]
 [1238 1403]]
Accuracy = 78.56089920766539
Precision = 56.30016051364366
Recall = 53.12381673608482
F1-Score = 54.66588739528541


Model No.6
Confusion Matrix:
[[7133 1114]
 [1130 1477]]
Accuracy = 79.32559425096738
Precision = 57.00501736781166
Recall = 56.65515

## K Nearest Neighbors (3 Neighbors) using Scikit Learn

In [37]:
# K Nearest Neighbours (No. of Neighbors = 3)
accuracy_list = np.zeros(10)
precision_list = np.zeros(10)
recall_list = np.zeros(10)
f1_list = np.zeros(10)
for i in range(10):
    
    x_train, x_test, y_train, y_test = train_test_split(new_dataset, target, test_size=1/3)
    
    knn = KNeighborsClassifier(n_neighbors=3)
    knn.fit(x_train, y_train)
    y_pred = knn.predict(x_test)
    
    print(f"Model No.{i+1}")
    print(f"Confusion Matrix:\n{metrics.confusion_matrix(y_test, y_pred)}")
    print(f"Accuracy = {metrics.accuracy_score(y_test, y_pred)*100}")
    print(f"Precision = {metrics.precision_score(y_test, y_pred)*100}")
    print(f"Recall = {metrics.recall_score(y_test, y_pred)*100}")
    print(f"F1-Score = {metrics.f1_score(y_test, y_pred)*100}")
    
    accuracy_list[i] =  metrics.accuracy_score(y_test, y_pred)*100
    precision_list[i] = metrics.precision_score(y_test, y_pred)*100
    recall_list[i] =  metrics.recall_score(y_test, y_pred)*100
    f1_list[i] = metrics.f1_score(y_test, y_pred)*100
    print("\n")
    
print(f"Accuracy:\n Mean = {accuracy_list.mean()}  Standard Deviation = {accuracy_list.std()}")
print(f"Precision:\n Mean = {precision_list.mean()}  Standard Deviation = {precision_list.std()}")
print(f"Recall:\n Mean = {recall_list.mean()}  Standard Deviation = {recall_list.std()}")
print(f"F1-Score:\n Mean = {f1_list.mean()}  Standard Deviation = {f1_list.std()}")

Model No.1
Confusion Matrix:
[[7360  856]
 [1156 1482]]
Accuracy = 81.46305509489589
Precision = 63.387510692899916
Recall = 56.17892342683851
F1-Score = 59.565916398713824


Model No.2
Confusion Matrix:
[[7298  952]
 [1117 1487]]
Accuracy = 80.93790307720656
Precision = 60.96760967609676
Recall = 57.104454685099846
F1-Score = 58.972833630775334


Model No.3
Confusion Matrix:
[[7330  850]
 [1168 1506]]
Accuracy = 81.40777593513911
Precision = 63.92190152801358
Recall = 56.32011967090501
F1-Score = 59.88071570576541


Model No.4
Confusion Matrix:
[[7322  892]
 [1182 1458]]
Accuracy = 80.89183711074259
Precision = 62.04255319148936
Recall = 55.22727272727273
F1-Score = 58.436873747495


Model No.5
Confusion Matrix:
[[7316  935]
 [1148 1455]]
Accuracy = 80.80891837110742
Precision = 60.87866108786611
Recall = 55.89704187475989
F1-Score = 58.281594231924686


Model No.6
Confusion Matrix:
[[7378  890]
 [1114 1472]]
Accuracy = 81.53676064123825
Precision = 62.32006773920406
Recall = 56.92188